### PR TITLE
Refactor input and output configuration components

### PR DESCRIPTION
**Pull request by mslinger**
Refactors the input and output process so there are two new components, input file config and output file config, where you can add a component for the desired data type to get new parameters. It should simplify the process of getting new parameter data.

### CODE REVIEW

**Review by joembarron — APPROVED** [review]
Screen Shot 2024-11-02 at 11 10 29 AM
Approved. Maybe we can adjust the font size of this button so it doesn't hang over the edge.

**Comment by mslinger** [comment]
That's interesting because on my system it's fine. I can adjust width.

**Comment by joembarron** [comment]
> That's interesting because on my system it's fine. I can adjust width.

On Mac, I can't seem to change the window size. It's fixed.

**Comment by mslinger** [comment]
Yeah, eventually the window will be made resizable. I sent a message in slack, if you didn't see it.

**Pull request merged**
